name: Run Python Script

on:
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Latest version, no name needed
      - uses: actions/setup-python@v5 # Latest version
        with:
          python-version: '3.x'
      - run: python src/add_numbers.py # Combines "name" and "run"
        env:
          NUM1: 10
